config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'dashboard#index'
  resources :tree_applications
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tree_application.rb
class TreeApplication < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_user!

  def index
  end
end

app/controllers/tree_applications_controller.rb
class TreeApplicationsController < ApplicationController
  before_action :authenticate_user!

  def index
    @tree_applications = TreeApplication.all
  end

  def new
    @tree_application = TreeApplication.new
  end

  def create
    tree_application = TreeApplication.create(tree_application_params)
    redirect_to action: "show", id: tree_application.id
  end

  def show
    @tree_application = TreeApplication.find(params[:id])
  end

  private

  def tree_application_params
    params.require(:tree_application).permit(:first_name,
                                             :last_name,
                                             :address_1,
                                             :address_2,
                                             :city,
                                             :state,
                                             :zip_code,
                                             :country,
                                             :phone_number,
                                             :email,
                                             :rental_property,
                                             :inquiry_date,
                                             :fee_amount,
                                             :referral_source,
                                             :water_agreement)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/tree_applications_helper.rb
module TreeApplicationsHelper
end

app/views/dashboard/index.html.haml
= link_to 'Tree Applications', tree_applications_path, class: 'btn btn-primary'

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OakFlatTree</title>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= yield %>
  </body>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

  <!-- Optional theme -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</html>

app/views/tree_applications/_form.html.haml
.tree-application
  = form_for @tree_application, html: { class: 'form-horizontal' } do |f|
    .form-group
      = f.label :first_name, class: 'col-sm-1 control-label'
      = f.text_field :first_name, class: 'col-sm-1'
      = f.label :last_name, class: 'col-sm-1 control-label'
      = f.text_field :last_name, class: 'col-sm-1'
    .form-group
      = f.label :address_1, class: 'col-sm-1 control-label'
      = f.text_field :address_1, class: 'col-sm-3'
    .form-group
      = f.label :address_2, class: 'col-sm-1 control-label'
      = f.text_field :address_2, class: 'col-sm-3'
    .form-group
      = f.label :city, class: 'col-sm-1 control-label'
      = f.text_field :city, class: 'col-sm-1', value: 'Oakland'
      = f.label :state, class: 'col-sm-1 control-label'
      = f.text_field :state, class: 'col-sm-1', value: 'CA'
    .form-group
      = f.label :zip_code, class: 'col-sm-1 control-label'
      = f.text_field :zip_code, class: 'col-sm-1'
      = f.label :country, class: 'col-sm-1 control-label'
      = f.text_field :country, class: 'col-sm-1'
    .form-group
      = f.label :email, class: 'col-sm-1 control-label'
      = f.email_field :email, class: 'col-sm-3'
    .form-group
      = f.label :phone_number, class: 'col-sm-1 control-label'
      = f.telephone_field :phone_number, class: 'col-sm-1'
      = f.label :rental_property, class: 'col-sm-1 control-label'
      = f.select :rental_property, [true, false], include_blank: true, class: 'col-sm-1'
    .form-group
      = f.label :inquiry_date, class: 'col-sm-1 control-label'
      = f.date_field :inquiry_date, class: 'col-sm-3'
    .form-group
      = f.label :referral_source, class: 'col-sm-1 control-label'
      = f.text_field :referral_source, class: 'col-sm-3'
    .form-group
      = f.label :fee_amount, class: 'col-sm-1 control-label'
      = f.number_field :fee_amount, class: 'col-sm-1'
      = f.label :water_agreement, class: 'col-sm-1 control-label'
      = f.select :water_agreement, [true, false], include_blank: true, class: 'col-sm-1'
    = f.submit 'Save Application', class: 'col-sm-4'

app/views/tree_applications/index.html.haml
= link_to 'New Tree Application', new_tree_application_path, class: 'btn btn-primary'

- @tree_applications.each do |app|
  .tree-application-row
    = app.id
    = app.first_name
    = app.last_name
    = link_to 'App', tree_application_path(app.id), class: 'btn btn-primary btn-xs'

app/views/tree_applications/new.html.haml
= render 'form'

app/views/tree_applications/show.html.haml
.h1
  = @tree_application.first_name + @tree_application.last_name